### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore.Commerce#580]
Using the same dockerfile than Orchard Core, which should work, fails to execute with an error 500.

2025-05-02 04:40:25.7948|ERROR|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HNC96DQA79HL", Request id "0HNC96DQA79HL:00000001": An unhandled exception was thrown by the application.|System.InvalidOperationException: The antiforgery system has the configuration value AntiforgeryOptions.Cookie.SecurePolicy = Always, but the current request is not an SSL request.

Tested on main branch.

**Comment by Skrypt** [comment]
More on this. After trying deploying a docker container behind a reverse proxy that serves the SSL key for all underlying services I could not make this work.

The issue is that something in OCC enforces using SSL for the AntiforgeryToken.
When using a reverse proxy you don't enforce using SSL in the docker container. You just serve it through HTTP and then the reverse proxy will take care of returning it to the client through its own SSL port. Everything in the private network can be done with HTTP. Also, normally this AntiforgeryToken should set itself to use SSL or not if we don't change its configuration.

So, my question is. Do you guys know which package does enforce SSL?

**Comment by Skrypt** [comment]
Here if we look at this enum: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.cookiesecurepolicy?view=aspnetcore-9.0

Normally the default should be "SameAsSite" which has been changed to "Always" somewhere in OCC.

**Comment by Skrypt** [comment]
So I found what triggers this.

ConfigureSecurityDefaultsWithStaticFiles in Program.cs

**Comment by Skrypt** [comment]
Ok, I confirm that removing the ConfigureSecurityDefaultsWithStaticFiles in Program.cs fixed my issue.
We should make this configurable so that by default we don't serve with HTTPS for docker containers behind a reverse proxy.

**Comment by Piedone** [comment]
@sarahelsaig please comment.

**Comment by Skrypt** [comment]
For reference here is the Docker compose file I used to make the SSL working in the container:

```
services:
  goride:
    image: goride-construction:latest
    container_name: goride
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "pa55w0rd!"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/OrchardCore.Commerce.Web.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
```

Which required that I create this OrchardCore.Commerce.Web.pfx file using this documentation:

https://learn.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-9.0
